#!/bin/bash

set -xe

yarn build --mode "$TARGET_ENV"
yarn build:funcs
firebase deploy -P "$TARGET_ENV"
yarn migrate
scripts/built-app-version | firebase -P $TARGET_ENV database:set /config/version -y
