#!/usr/bin/env node

const { run, initializeFirebase } = require('./helpers');

run(async () => {
  const [email] = process.argv.slice(2);

  if (!email) {
    throw 'Usage: ./scripts/unverify-user <email>';
  }

  console.log(`Manually unverifying email address for user: ${email}`);

  const { auth } = await initializeFirebase();

  const user = await auth.getUserByEmail(email);

  await auth.setCustomUserClaims(user.uid, { pairistValidEmail: false });

  console.log('Done!');
});
